FROM bitnami/spark:3.5.1

USER root

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER 1001

WORKDIR /opt/spark-app

COPY ./app /opt/spark-app
COPY .env /opt/spark-app/.env
